### ISSUE TITLE
DynamicVoice wishlist

### ISSUE THREAD

**Issue by HelmicNewciv** [Kowlin/refactored-cogs#23]
- Ability to set the naming scheme of dynamic voice channels (e.g. Rust Server # 3)
- Multiple groups of dynamic voice channels.  A gaming community might want dynamic Rust and Overwatch channels with their own independent settings.
- Ability to define settings by referencing an example voice channel.  For example, the admin might create a channel called Overwatch # 1, and that channel will have various permissions set up and limits on how many people can join it.  The admin could then type !dynamicvoice creategroup Overwatch and all those settings would be used to generate dynamic channels.
- Using that base channel, determine the position of new dynamic channels.

**Comment by Kowlin** [comment]
Merge into #26
