### ISSUE TITLE
antilink

### ISSUE THREAD

**Issue by CreativeCodeCat** [Kowlin/refactored-cogs#9]
- Cog: antilink
- Issue description: Error 
- Reproduction Steps: Not to sure 
- Traceback of error (Console):
Ignoring exception in message
Traceback (most recent call last):
  File "C:\Users\Wayne\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\Users\Wayne\Desktop\IIninetales\cogs\antilink.py", line 71, in _new_message
    if message.server.id in self.json:
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by skeith** [comment]
What were you doing to get that error?

**Comment by CreativeCodeCat** [comment]
someone posting a link to there discord

**Comment by Chovin** [comment]
~~that... should never happen
[![image](https://cloud.githubusercontent.com/assets/17536161/21447524/54bc7128-c921-11e6-88e1-4f3baaffbb9e.png)](https://github.com/Kowlin/refactored-cogs/blob/586259581dfb1dcb78014c2fce38b6cae3b78aff/antilink/antilink.py#L69-L71)
make sure your cog is updated:
`[p]cog update`~~

oh wait, I had a brain fart.
~~`pass`~~ -> `return`

**Comment by Chovin** [comment]
please update your cogs and try again.
feel free to reopen this issue if you're still getting this error
